/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    private App testQuoteApp;
    private Quote[] quotes = testQuoteApp.readFile();
    @Before public void setup(){
        App testQuoteApp = new App();
    }

    @Test public void testReadFile(){
        assertNotNull(quotes[0]);
    }

    @Test public void testGetRandomQuote(){

        assertNotNull(testQuoteApp.randomQuote(quotes));
    }
}
