/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {

    public static void main(String[] args) {
        System.out.println(randomQuote(readFile()));
    }

    public static Quote[] readFile() {

        Gson gson = new Gson();

        Quote[] quotes = new Quote[0];
        try {
            BufferedReader br = new BufferedReader(new FileReader("src/main/resources/recentquotes.json"));

            quotes = gson.fromJson(br, Quote[].class);

        } catch (FileNotFoundException e) {
            System.out.println(e);
        }

        return quotes;

    }

    public static String  randomQuote(Quote[] quotes) {
        return quotes[(int)(Math.random()*quotes.length)].quoteAndAuthorString();
    }



}
