/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {

    public static void main(String[] args) {
        webRequest();
    }

    public static Quote[] readFile() {

        Gson gson = new Gson();

        Quote[] quotes = new Quote[0];
        try {
            BufferedReader br = new BufferedReader(new FileReader("src/main/resources/recentquotes.json"));

            quotes = gson.fromJson(br, Quote[].class);

        } catch (FileNotFoundException e) {
            System.out.println(e);
        }

        return quotes;

    }

    public static String  randomQuote(Quote[] quotes) {
        return quotes[(int)(Math.random()*quotes.length)].quoteAndAuthorString();
    }

    public static void webRequest(){
        URL url = null;
        try {
            url = new URL("http://swquotesapi.digitaljedi.dk/api/SWQuote/RandomStarWarsQuote");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HttpURLConnection con = null;
        try {
            con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");
            BufferedReader in = new BufferedReader(
                    new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer content = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();
            System.out.println(content.toString());
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
